image:
  file: .gitpod.Dockerfile

# List the ports you want to expose and what to do when they are served. See https://www.gitpod.io/docs/43_config_ports/
ports:
- port: 8080

# List the start up tasks. You can start them in parallel in multiple terminals. See https://www.gitpod.io/docs/44_config_start_tasks/
tasks:
- before: flutter config --enable-web
  init: flutter channel master && flutter precache --web --force && flutter packages get # runs during prebuild
  command: flutter upgrade && flutter pub get && flutter pub upgrade
vscode:
  extensions:
    - Dart-Code.flutter@3.5.1:0FyuzXye7dV19PNst3+Llg==
    - Dart-Code.dart-code@3.5.1:W6zqgIED1gxtkBH/pbfGXA==